version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      docker: 20
  pre_build:
    on-failure: ABORT
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - "docker build -t php-app:v${CODEBUILD_BUILD_NUMBER} ."
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar